# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='no_stands',
            field=models.IntegerField(default=0),
        ),
    ]
